name: Jira ticket inserting

on:
  pull_request:
    branches:
      - main

jobs:
  get_branch_name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "the branch to be merged ${{ github.event.pull_request.head.ref }}"
      # isolate ticket number and capitalize it
      - run: echo "ticket=$(echo ${{ github.event.pull_request.head.ref }} | grep -oiE 'fws[- ][0-9]*' | sed 's/ /-/' | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
      - run: echo $ticket
      - run: echo "is it mergeable ? ${{ github.event.pull_request.mergeable_state }}"
  
  print_pr_body:
    runs-on: ubuntu-latest
    needs:
      - get_branch_name
    steps:
      - run: echo "your pr's body ${{ github.event.pull_request.body }}"
      - run: echo "link=$(echo "${{ github.event.pull_request.body }}" | grep "weforum.jira.com")" >> $GITHUB_ENV
      - run: echo $link