name: Jira ticket inserting

on:
  pull_request:
    branches:
      - main

jobs:
  get_branch_name:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.pull_request.head.ref }}  
