name: Lint Check

on:
  pull_request:
    types: [review_requested]
  # or
  # pull_request_review:
    #types: [submitted, edited]
    branches:
      - main

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository }}
      - run: echo ${{ github.actor }}
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run rubocop
        id: lint
        run: bundle exec rubocop
      - name: print linting outcome
        if: '!cancelled()'
        run: |
          if [ "${{ steps.lint.outcome }}" = "success" ]; then
            echo "linting successful."
            exit 0
          else
            echo "linting failed."
            exit 1
          fi
          
          