name: Lint Check

on:
  push:
    branches:
      - main

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ github.workspace }}
      - run: echo ${{ github.repository }}
      - run: echo ${{ github.action }}
      - run: echo ${{ github.actor }}
      - uses: actions/setup-ruby@v1
    