name: Lint Check

on:
  pull_request:
    types: [opened, review_requested]
  # or
  # pull_request_review:
    #types: [submitted, edited]
    branches:
      - main

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository }}
      - run: echo ${{ github.actor }}
      # checks out branch that triggered workflow
      - uses: actions/checkout@v4
      # use ruby version in .ruby_version file
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run rubocop
        id: lint
        run: bundle exec rubocop
      - name: print linting outcome
        # prefer always to  '!cancelled()' for logging
        if: ${{ always() }}
        run: |
          if [ "${{ steps.lint.outcome }}" = "success" ]; then
            echo "linting successful."
            exit 0
          else
            echo "linting failed."
            exit 1
          fi
          
          