name: Lint Check

on:
  push:
    branches:
      - main

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository }}
      - run: echo ${{ github.actor }}
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run rubocop
        id: lint
        run: bundle exec rubocop
      - name: print linting outcome
        if: '!cancelled()'
        run: |
          result=${{ (steps.lint.outcome) }}
          if [ $result="success" ]; then
            echo "Linting successful."
            exit 0
          else
            echo "Ling failed."
            exit 1
          fi
          
          